import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/dist/client/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full bg-gray-100 dark:bg-gray-950 flex items-center justify-center p-6">
        
        <ul className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          
          {/* Card 1 */}
          <li>
            <div className="bg-white dark:bg-gray-900 rounded-2xl p-6 shadow-md hover:shadow-xl transform hover:scale-105 transition-all duration-300 cursor-pointer">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                Calendar Project
              </h3>

              <p className="text-gray-500 dark:text-gray-400 mb-3">
                Credentials:
              </p>

              <ul className="text-sm text-gray-600 dark:text-gray-300 space-y-1">
                <li>username: admin</li>
                <li>password: admin</li>
              </ul>
            </div>
          </li>

          {/* Card 2 */}
          <li>
           <Link href="/calendar"> <div className="bg-white dark:bg-gray-900 rounded-2xl p-6 shadow-md hover:shadow-xl transform hover:scale-105 transition-all duration-300 cursor-pointer">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                Purchase Project
              </h3>

              <p className="text-gray-500 dark:text-gray-400 mb-3">
                Credentials:
              </p>

              <ul className="text-sm text-gray-600 dark:text-gray-300 space-y-1">
                <li>username: admin</li>
                <li>password: admin</li>
              </ul>
            </div>
            </Link>
          </li>

          {/* Card 3 */}
          <li>
            <div className="bg-white dark:bg-gray-900 rounded-2xl p-6 shadow-md hover:shadow-xl transform hover:scale-105 transition-all duration-300 cursor-pointer">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                GLPI Project
              </h3>
                 <p className="text-gray-500 dark:text-gray-400 mb-3">
                Credentials:
              </p>
              <ul className="text-sm text-gray-600 dark:text-gray-300 space-y-1">
                <li>username: </li>
                <li>password: </li>
              </ul>
            </div>
          </li>

        </ul>

      </body>
    </html>
  );
}